// dummyQuestions.js
export const dummyQuestions = [
  {
    id: 1,
    type: 'Quantitative',
    difficulty: 'easy',
    question: 'What is 2 + 2?',
    options: ['2', '3', '4', '5'],
  },
  {
    id: 2,
    type: 'Quantitative',
    difficulty: 'medium',
    question: 'What is 5 * 6?',
    options: ['11', '30', '60', '25'],
  },
  {
    id: 3,
    type: 'Logical Reasoning',
    difficulty: 'easy',
    question: 'Which of the following is a prime number?',
    options: ['4', '6', '8', '11'],
  },
  {
    id: 4,
    type: 'Logical Reasoning',
    difficulty: 'hard',
    question: 'Complete the sequence: 2, 4, 8, 16, ?',
    options: ['18', '20', '32', '64'],
  },
  {
    id: 5,
    type: 'Verbal',
    difficulty: 'medium',
    question: 'What is the synonym of "happy"?',
    options: ['Sad', 'Joyful', 'Angry', 'Hungry'],
  },
  {
    id: 6,
    type: 'Verbal',
    difficulty: 'easy',
    question: 'What is the antonym of "generous"?',
    options: ['Kind', 'Mean', 'Caring', 'Polite'],
  },
  {
    id: 7,
    type: 'Quantitative',
    difficulty: 'easy',
    question: 'What is 7 + 3?',
    options: ['9', '10', '11', '12'],
  },
  {
    id: 8,
    type: 'Quantitative',
    difficulty: 'medium',
    question: 'What is 12 / 4?',
    options: ['2', '3', '4', '5'],
  },
  {
    id: 9,
    type: 'Quantitative',
    difficulty: 'hard',
    question: 'What is 15 * 3?',
    options: ['40', '45', '50', '55'],
  },
  {
    id: 10,
    type: 'Quantitative',
    difficulty: 'medium',
    question: 'What is 8 - 5?',
    options: ['2', '3', '4', '5'],
  },
  {
    id: 11,
    type: 'Logical Reasoning',
    difficulty: 'easy',
    question: 'If all roses are flowers and some flowers are red, can we say some roses are red?',
    options: ['Yes', 'No', 'Not enough information', 'None of the above'],
  },
  {
    id: 12,
    type: 'Logical Reasoning',
    difficulty: 'medium',
    question: 'What comes next in the series: 1, 2, 4, 8, ?',
    options: ['10', '12', '14', '16'],
  },
  {
    id: 13,
    type: 'Logical Reasoning',
    difficulty: 'hard',
    question: 'Find the next term in the pattern: 5, 10, 15, 20, ?',
    options: ['22', '23', '25', '30'],
  },
  {
    id: 14,
    type: 'Logical Reasoning',
    difficulty: 'medium',
    question: 'Which number should come next in the series: 2, 5, 10, 17, ?',
    options: ['24', '25', '26', '27'],
  },
  {
    id: 15,
    type: 'Verbal',
    difficulty: 'easy',
    question: 'What is a synonym for "fast"?',
    options: ['Quick', 'Slow', 'Steady', 'Heavy'],
  },
  {
    id: 16,
    type: 'Verbal',
    difficulty: 'medium',
    question: 'What is the antonym of "ancient"?',
    options: ['Old', 'Modern', 'Recent', 'Historical'],
  },
  {
    id: 17,
    type: 'Verbal',
    difficulty: 'hard',
    question: 'What is the synonym of "arduous"?',
    options: ['Easy', 'Difficult', 'Light', 'Fun'],
  },
  {
    id: 18,
    type: 'Verbal',
    difficulty: 'medium',
    question: 'What is the antonym of "loyal"?',
    options: ['Faithful', 'Unfaithful', 'Trustworthy', 'Dedicated'],
  },
  {
    id: 19,
    type: 'Quantitative',
    difficulty: 'medium',
    question: 'What is 5 squared?',
    options: ['20', '25', '30', '35'],
  },
  {
    id: 20,
    type: 'Quantitative',
    difficulty: 'hard',
    question: 'What is the value of 2^4?',
    options: ['8', '12', '14', '16'],
  },
  {
    id: 21,
    type: 'Logical Reasoning',
    difficulty: 'easy',
    question: 'If some cats are not dogs, can we say no cats are dogs?',
    options: ['Yes', 'No', 'Not enough information', 'None of the above'],
  },
  {
    id: 22,
    type: 'Logical Reasoning',
    difficulty: 'medium',
    question: 'What comes next in the sequence: 3, 9, 27, 81, ?',
    options: ['162', '243', '324', '400'],
  },
  {
    id: 23,
    type: 'Verbal',
    difficulty: 'medium',
    question: 'What is a synonym for "benevolent"?',
    options: ['Malevolent', 'Kind', 'Hostile', 'Apathetic'],
  },
  {
    id: 24,
    type: 'Verbal',
    difficulty: 'hard',
    question: 'What is the antonym of "serene"?',
    options: ['Calm', 'Agitated', 'Peaceful', 'Relaxed'],
  },
  {
    id: 25,
    type: 'Quantitative',
    difficulty: 'medium',
    question: 'What is 3 * 7?',
    options: ['19', '20', '21', '22'],
  },
  {
    id: 26,
    type: 'Quantitative',
    difficulty: 'hard',
    question: 'What is 144 / 12?',
    options: ['10', '11', '12', '13'],
  },
  {
    id: 27,
    type: 'Logical Reasoning',
    difficulty: 'medium',
    question: 'Which number is the odd one out: 4, 8, 12, 16, 18?',
    options: ['4', '8', '12', '18'],
  },
  {
    id: 28,
    type: 'Logical Reasoning',
    difficulty: 'hard',
    question: 'If A > B and B > C, what can we say about A and C?',
    options: ['A > C', 'A < C', 'A = C', 'Not enough information'],
  },
  {
    id: 29,
    type: 'Verbal',
    difficulty: 'easy',
    question: 'What is the synonym of "genuine"?',
    options: ['Fake', 'Authentic', 'False', 'Phony'],
  },
  {
    id: 30,
    type: 'Verbal',
    difficulty: 'medium',
    question: 'What is the antonym of "vivid"?',
    options: ['Bright', 'Dull', 'Clear', 'Sharp'],
  },
  {
    id: 31,
    type: 'Quantitative',
    difficulty: 'easy',
    question: 'What is 9 + 1?',
    options: ['10', '11', '9', '8'],
  },
  {
    id: 32,
    type: 'Quantitative',
    difficulty: 'medium',
    question: 'What is 20 - 7?',
    options: ['13', '14', '15', '16'],
  },
  {
    id: 33,
    type: 'Logical Reasoning',
    difficulty: 'medium',
    question: 'What comes next in the series: 1, 4, 7, 10, ?',
    options: ['11', '12', '13', '14'],
  },
  {
    id: 34,
    type: 'Logical Reasoning',
    difficulty: 'hard',
    question: 'Find the next term in the pattern: 3, 5, 7, 11, ?',
    options: ['13', '15', '17', '19'],
  },
  {
    id: 35,
    type: 'Verbal',
    difficulty: 'medium',
    question: 'What is the synonym of "ambiguous"?',
    options: ['Clear', 'Uncertain', 'Definite', 'Straightforward'],
  },
  {
    id: 36,
    type: 'Verbal',
    difficulty: 'hard',
    question: 'What is the antonym of "fragile"?',
    options: ['Strong', 'Weak', 'Brittle', 'Delicate'],
  },
  {
    id: 37,
    type: 'Quantitative',
    difficulty: 'hard',
    question: 'What is 5 cubed?',
    options: ['125', '150', '175', '200'],
  },
  {
    id: 38,
    type: 'Quantitative',
    difficulty: 'medium',
    question: 'What is 18 % 5?',
    options: ['3', '4', '2', '1'],
  },
  {
    id: 39,
    type: 'Logical Reasoning',
    difficulty: 'easy',
    question: 'If all birds can fly and some birds are blue, can we say some blue things can fly?',
    options: ['Yes', 'No', 'Not enough information', 'None of the above'],
  },
  {
    id: 40,
    type: 'Logical Reasoning',
    difficulty: 'hard',
    question: 'What comes next in the series: 5, 11, 17, 23, ?',
    options: ['29', '30', '31', '32'],
  },
  {
    id: 41,
    type: 'Verbal',
    difficulty: 'medium',
    question: 'What is a synonym for "deceptive"?',
    options: ['Honest', 'Misleading', 'Truthful', 'Reliable'],
  },
  {
    id: 42,
    type: 'Verbal',
    difficulty: 'hard',
    question: 'What is the antonym of "complex"?',
    options: ['Simple', 'Complicated', 'Intricate', 'Detailed'],
  },
  {
    id: 43,
    type: 'Quantitative',
    difficulty: 'easy',
    question: 'What is 4 + 5?',
    options: ['8', '9', '10', '11'],
  },
  {
    id: 44,
    type: 'Quantitative',
    difficulty: 'medium',
    question: 'What is 14 - 6?',
    options: ['7', '8', '9', '10'],
  },
  {
    id: 45,
    type: 'Logical Reasoning',
    difficulty: 'medium',
    question: 'Which number completes the series: 2, 5, 10, 17, ?',
    options: ['22', '23', '24', '25'],
  },
  {
    id: 46,
    type: 'Logical Reasoning',
    difficulty: 'hard',
    question: 'Which number is the odd one out: 1, 4, 9, 16, 25, 30?',
    options: ['1', '4', '9', '30'],
  },
  {
    id: 47,
    type: 'Verbal',
    difficulty: 'easy',
    question: 'What is a synonym for "angry"?',
    options: ['Happy', 'Upset', 'Excited', 'Calm'],
  },
  {
    id: 48,
    type: 'Verbal',
    difficulty: 'medium',
    question: 'What is the antonym of "generous"?',
    options: ['Kind', 'Mean', 'Giving', 'Charitable'],
  },
  {
    id: 49,
    type: 'Quantitative',
    difficulty: 'hard',
    question: 'What is the value of 3^3?',
    options: ['6', '9', '27', '81'],
  },
  {
    id: 50,
    type: 'Quantitative',
    difficulty: 'medium',
    question: 'What is 100 divided by 4?',
    options: ['20', '25', '30', '40'],
  },
];
